services:
    pix_coin_db:
        image: mysql:8.0
        container_name: pix_coin_database
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: pixcoin
            MYSQL_USER: pixcoin
            MYSQL_PASSWORD: p!xc0!n
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

volumes:
    db_data:
        driver: local

networks:
    laravel_network:
        driver: bridge
